### ISSUE TITLE
Revised approach to event forwarding, without searching for ScreenView

### ISSUE THREAD

**Issue by Denz1994** [phetsims/projectile-motion#20] opened 2017-03-21 17:12 UTC
Events in the toolbox require a coordinate transformation from the toolbox's frame of reference to the screen view's frame of reference. Using the measuring tape node's and tracer node's parent (which is the screen view), we can avoid searching for the screen view.

A solution may involve something like this:

```js
tracerNode.globalToParentPoint(new Vector2())
```

This removes the redundancy of having to search for the screen view  for every coordinate transform.

Reference: https://github.com/phetsims/masses-and-springs/issues/58

**Comment by pixelzoom** [comment] 2017-04-25 02:24
To be clear... This is the bit of code that needs to go away, ToolboxPanel, line 66:

```js
      // find the parent screen if not already found by moving up the scene graph
      if ( !parentScreenView ) {
        var testNode = self;
        while ( testNode !== null ) {
          if ( testNode instanceof ScreenView ) {
            parentScreenView = testNode;
            break;
          }
          testNode = testNode.parents[ 0 ]; // move up the scene graph by one level
        }
        assert && assert( parentScreenView, 'unable to find parent screen view' );
      }
```

This approach is in several sims (area-builder, arithmetic, balancing-act, energy-forms-and-changes, expression-exchange, least-squares-regression).  I'm guessing therefore that it originated with @jbphet.

**Comment by pixelzoom** [comment] 2017-04-25 02:39
See https://github.com/phetsims/scenery-phet/issues/214#issuecomment-174014179 for ways to improve this.

**Comment by andrea-phet** [comment] 2017-07-17 16:47
Assigning to @Denz1994 to review and close.

**Comment by Denz1994** [comment] 2017-07-17 17:01
While looking over commit a76e01e, it seems to follow the suggestion made in  phetsims/scenery-phet#214 (comment). We are no longer searching for a ScreenView parent but use the parent (which is a ScreenView) of the tracerNode and measuringTapeNode.

Before closing, are there any other suggestions from @pixelzoom that you think would be useful. I noticed that phetsims/scenery-phet#214  is up for dev meeting, so has this event forwarding approach changed recently?

**Comment by pixelzoom** [comment] 2017-07-17 17:47
I have not used this creator pattern, I only identified it as an anti-pattern.  I suggest that you have @jbphet review your changes, since he invented the "search for parent ScreenView" approach, then converted his sims like you're doing here.

That said... A couple of things that I do notice about the changes in https://github.com/phetsims/projectile-motion/commit/a76e01e37a7cfe89d9a80f6a96719aa55b34e933:

(1) This comment:
`75  // since this is a panel, the parent is the screen view, and the screen view is the parent of tracerNode`

... indicates that the parent must be a ScreenView.  But I see no verification of that in the code.  There's a similar problem with measuringTapeNode.  See below for how/where to address this.

(2) These assertions at the top of the constructor are ineffective:

```js
    assert && assert ( this.parent === measuringTapeNode.parent, ... );
    assert && assert ( this.parent === tracerNode.parent, ... );
```

They are succeeding only because `this.parent`, `measuringTapeNode.parent` and `tracerNode.parent` are all `undefined` when the constructor is called.  They have not been added to the scenegraph, and the supertype constructor hasn't been called.   And even if they had been added to the scenegraph, there is no such thing as `this.parent`, that ES5 getter doesn't exist.

Delete the above assertions.  Then add these assertions these assertion:

```js
tracerNode.isUserControlledProperty.lazyLink( function( isUserControlled ) {
  assert && assert( tracerNode.getParent() instanceof ScreenView );
  assert && assert( traceNode.getParent()=== self.getParent() );
  ...
} );

...

measuringTapeNode.isBaseUserControlledProperty.lazyLink( function( isUserControlled ) {
  assert && assert( measuringTapeNode.getParent() instanceof ScreenView );
  assert && assert( measuringTapeNode.getParent()=== self.measuringTapeNode() );
} );
```

**Comment by pixelzoom** [comment] 2017-07-17 17:48
Note: @jonathanolson just added ES5 getter for `parent` to Node, so feel free to use `.parent` instead of `.getParent` in the above.

**Comment by Denz1994** [comment] 2017-07-17 19:42
Thanks for the input @pixelzoom.

I am going to remain assigned to this issue to learn from the follow-up after @jbphet review, and I think he should close this after any changes rather than me.

**Comment by jbphet** [comment] 2017-07-19 18:24
For the most part, the commit above looks reasonable, except that there is a duplicated line of code.  Here is an excerpt:

```js
        // ignore this if already dragging
        if ( event.pointer.dragging ) { return; }

        // don't try to start drags with a right mouse button or an attached pointer
        if ( !event.canStartPress() ) { return; }

        // Don't try to start drags with a right mouse button or an attached pointer.
        if ( !event.canStartPress() ) { return; }
```

The duplication should be fixed.  After that, please leave this issue unassigned but open, and we will revisit it when the simulation is getting closer to publication.  The solution for event forwarding is currently evolving, with details found in https://github.com/phetsims/scenery/issues/639, so it would be good to update to the latest approach at some point, but it isn't quite ready yet.

**Comment by andrea-phet** [comment] 2017-07-19 18:44
Thanks for catching that. I fixed it, and will just leave this issue open.

**Comment by andrea-phet** [comment] 2017-07-19 18:45
@Denz1994 I'm removing your assignment but you can assign yourself back if you want to follow this.

**Comment by pixelzoom** [comment] 2017-07-19 19:04
@jbphet said:
> The solution for event forwarding is currently evolving, with details found in phetsims/scenery#639, so it would be good to update to the latest approach at some point, but it isn't quite ready yet.

Information about the "creator pattern" is supposed to live in phetsims/scenery-phet#214.  But it's currently leaking over into phetsims/scenery#639 (where things are currently broken).  So @andrea-phet you may need to monitor both issues until we can get phetsims/scenery#639 fixed, and phetsims/scenery-phet#214 in sync with reality.

**Comment by samreid** [comment] 2017-08-03 18:13
@andrea-phet will take a look and let me and @jbphet know if anything else is needed.

**Comment by andrea-phet** [comment] 2017-08-07 16:00
@jbphet could you review the above commit?

**Comment by pixelzoom** [comment] 2017-08-10 21:29
Based on my understanding of `createForwardingListener` and the usages I see in CCK, this looks correct. Closing.

**Closed by pixelzoom** 2017-08-10 21:29 UTC
Labels: dev:code-review, status:ready-for-review
