### ISSUE TITLE
Tracer tool jumps from mouse

### ISSUE THREAD

**Issue by phet-steele** [phetsims/projectile-motion#143] opened 2017-08-17 15:53 UTC
This occurs to varying degrees at different zoom levels. Zoomed completely out is most dramatic:

1. Zoom all the way out on whatever screen.
2. Click and release the tracer tool (pick it up from and drop it back into the tool box). This behaves normally.
3. Click and hold a second time. The tool now jumps much farther away from your mouse than it should. This continues every time you grab the tracer from the tool box until you change zoom level.

This does NOT happen with the measuring tape. This DOES also occur with touch.

Seen on macOS 10.12.6 Chrome & FF. For phetsims/QA/issues/39.

URL: http://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.0-rc.1/projectile-motion_en.html
Version: 1.0.0-rc.1 2017-08-16 00:04:04 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"b7268ab0","branch":"HEAD"},"babel":{"sha":"d436176d","branch":"master"},"brand":{"sha":"90738131","branch":"HEAD"},"chipper":{"sha":"bccad091","branch":"HEAD"},"dot":{"sha":"f7d9de8b","branch":"HEAD"},"joist":{"sha":"7d518ed4","branch":"HEAD"},"kite":{"sha":"dc5c4382","branch":"HEAD"},"phet-core":{"sha":"6bfeef5c","branch":"HEAD"},"phetcommon":{"sha":"7ec5d299","branch":"HEAD"},"projectile-motion":{"sha":"77666df9","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"41bc57fb","branch":"HEAD"},"scenery-phet":{"sha":"4a9502e1","branch":"HEAD"},"sherpa":{"sha":"7be57a56","branch":"HEAD"},"sun":{"sha":"7b2c6f33","branch":"HEAD"},"tandem":{"sha":"74233a04","branch":"HEAD"}}

**Comment by pixelzoom** [comment] 2017-08-17 16:43
Reproduced.   The problem also occurs if you only zoom out 1 level - click on the tracer tool as described above, and it will be in a different position the second time.

The tracer tool and tape measure (TracerNode and MeasuringTapeNode respectively) are created in ProjectileMotionScreenView.  I'm a little confused about why MeasuringTapeNode is instantiated with a static model-view transform (`modelViewTransform: transformProperty.get()`), while TracerNode is instantiated with a dynamic model-view transform (`transformProperty`).  This may account for the fact that the problem is exhibited by the tracer tool, but not the measuring tape.

Positioning of the tracer tool and tape measure are handled in ToolboxPanel.  Positioning of the tracer tool:

```js
83 var tracerOriginPosition = tracerNode.globalToParentPoint( tracerNode.localToGlobalPoint( tracer.positionProperty.get() ) );
84
85 // coordinates empirically determined to shift tracer to mouse when pulled out of the toolbox
86 var initialViewPosition = tracerNode.globalToParentPoint( event.pointer.point ).minus( tracerOriginPosition );
87 tracer.positionProperty.set( transformProperty.get().viewToModelPosition( initialViewPosition ) );
```

Positioning of the measuring tape confuses me, code below. Why is tracerNode involved in this (lines 119 and 120)?

```js
119 var tapeBasePosition = tracerNode.globalToParentPoint( measuringTapeNode.localToGlobalPoint( measuringTapeNode.getLocalBaseCenter() ) );
120 var initialViewPosition = tracerNode.globalToParentPoint( event.pointer.point ).minus( tapeBasePosition );
121 measuringTape.basePositionProperty.set( transformProperty.get().viewToModelPosition( initialViewPosition ) );
122 measuringTape.tipPositionProperty.set( measuringTape.basePositionProperty.get().plus( tipToBasePosition ) );
```

**Comment by pixelzoom** [comment] 2017-08-17 16:46
I said:
> Positioning of the measuring tape confuses me, code below. Why is `tracerNode` involved ... ?

I suspect that `tracerNode` is involved due to a copy-paste error.

It looks like it is safe to change these lines in ToolboxPanel:

```js
119 var tapeBasePosition = tracerNode.globalToParentPoint( measuringTapeNode.localToGlobalPoint( measuringTapeNode.getLocalBaseCenter() ) );
120 var initialViewPosition = tracerNode.globalToParentPoint( event.pointer.point ).minus( tapeBasePosition );
```
to this:

```js
119 var tapeBasePosition = measuringTapeNode.globalToParentPoint( measuringTapeNode.localToGlobalPoint( measuringTapeNode.getLocalBaseCenter() ) );
120 var initialViewPosition = measuringTapeNode.globalToParentPoint( event.pointer.point ).minus( tapeBasePosition );
```

@andrea-phet recommended to make this change as part of fixing this issue.

**Comment by pixelzoom** [comment] 2017-08-17 20:23
@andrea-phet I have not isolated the cause of this problem, will leave that to you. So this issue is ready for you to work on it when you are available.

**Comment by pixelzoom** [comment] 2017-08-17 20:26
Btw... Imo, this issue would be nice to address before 1.0.0 release, but not absolutely necessary. The sim is still quite usable. @arouinfar do you agree?

**Comment by arouinfar** [comment] 2017-08-17 23:50
Agreed @pixelzoom. I think it would be nice to address before release, if possible.

**Comment by andrea-phet** [comment] 2017-08-18 02:48
The line that was buggy was `83 var tracerOriginPosition = tracerNode.globalToParentPoint( tracerNode.localToGlobalPoint( tracer.positionProperty.get() ) );` because `tracer.positionProperty.get()` was in model units, where as `localToGlobaPoint` should be taking view units. Anyhow, this shift is not needed, so I removed it.

Bug should be fixed on master, assigning to @phet-steele to check.

**Comment by pixelzoom** [comment] 2017-08-18 15:45
I verified the behavior is fixed, and the implementation looks good.  But the fix was only made in master.  @andrea-phet you'll need to also make the change in the 1.0 branch:

```
% cd projectile-motion
% git checkout 1.0
% git checkout master -- js/common/view/ToolboxPanel.js
% git commit -m "fix for #143"
% git push
% git checkout master
```

This fix _will_ require another RC, but will not require a full test matrix - spot testing on 1 or 2 platforms will be sufficient.

**Comment by pixelzoom** [comment] 2017-08-18 15:59
@andrea-phet Also good to add the "status:ready-to-test" label to issues that are ready for QA.

**Comment by andrea-phet** [comment] 2017-08-18 20:08
Okay. Fix added to 1.0.

**Comment by pixelzoom** [comment] 2017-08-23 17:01
This issue is ready for regression testing in 1.0.0-rc.2.

**Comment by lmulhall-phet** [comment] 2017-08-23 21:41
Fixed. Closing.

**Closed by lmulhall-phet** 2017-08-23 21:41 UTC
Labels: status:fixed-pending-testing, type:bug
