### ISSUE TITLE
CT timeToGround NaN

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-motion#228] opened 2020-05-08 15:19 UTC
```
projectile-motion : phet-io-fuzz : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/projectile-motion/projectile-motion_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22phet-io-fuzz%22%2C%22require.js%22%5D%2C%22snapshotName%22%3A%22snapshot-1588900082851%22%2C%22timestamp%22%3A1588936622801%7D&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: timeToGround: NaN, previousPoint.velocity: Vector2(0, 0), previousPoint.acceleration: Vector2(0, 0), fromIf: true
Error: Assertion failed: timeToGround: NaN, previousPoint.velocity: Vector2(0, 0), previousPoint.acceleration: Vector2(0, 0), fromIf: true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/assert/js/assert.js:22:13)
at Trajectory.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/projectile-motion/js/common/model/Trajectory.js:245:19)
at DragModel.stepModelElements (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/projectile-motion/js/common/model/ProjectileMotionModel.js:318:44)
at EventTimer.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/phet-core/js/EventTimer.js:123:12)
at DragModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/projectile-motion/js/common/model/ProjectileMotionModel.js:306:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/joist/js/Sim.js:285:20
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/axon/js/Action.js:224:18)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/joist/js/Sim.js:943:31)
at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/joist/js/Sim.js:933:12)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/joist/js/Sim.js:916:12)
id: Bayes Chrome
Snapshot from 5/7/2020, 7:08:02 PM
```

**Comment by jbphet** [comment] 2020-05-08 18:43
@zepumph - this appears to me to be a duplicate of #215, which apparently just crops up occasionally.  Assigning to you to determine whether to just close this one and continue working on the original.  If you do, please note in the original that the problem cropped up again.

**Comment by zepumph** [comment] 2020-05-18 19:22
Duplicate indeed! And on my list once phet-io priorities come back around to this sim.

**Closed by zepumph** 2020-05-18 19:22 UTC
Labels: type:automated-testing
