### ISSUE TITLE
[iPad 2] Path, cannon, and tool clipping

### ISSUE THREAD

**Issue by phet-steele** [phetsims/projectile-motion#129] opened 2017-07-26 21:33 UTC
@jonathanolson @andrea-phet, my gut is telling me we have another case of phetsims/function-builder/issues/35 on our hands. *Important*: like the linked issue, only seeing this on iPad 2, iOS 9.3.5.

There's a few ways to see some clipping. @jonathanolson, before you ask, NONE of these work (no issue) with `?rootRenderer=canvas`, but the performance drops considerably.

1. Into screen, set height to 4 meters and angle to 90. Everything else is default.
2. Fire, wait for the projectile to hit the ground. You will probably see all the dots disappear.

![img_0089](https://user-images.githubusercontent.com/5863899/28644610-77283130-7217-11e7-9684-21e8b8b04bb2.PNG)

3. Change the angle to 85.
4. Fire. Lots of fun things happen here, including the path from step 2 disappearing, or only being drawn partially, or just flickering. Even part of the cannon's stand is gone.

![img_0091](https://user-images.githubusercontent.com/5863899/28644611-772deada-7217-11e7-9907-ce62f9cb4c49.PNG)

5. Erase all paths
6. Drag the cannon up to 15 meters. Make sure you are still at default zoom (might not matter).
7. The Tracer tool, in the tool box, will be clipped. This doesn't happen all the time, and may require some iterations on moving the cannon up to 15 meters, back down, then back up. Might also rely on cannon angle.

![img_0092](https://user-images.githubusercontent.com/5863899/28644465-eee9f56a-7216-11e7-8ede-bbd558f6fd2b.PNG)

So far, I've only paths get clipped when something is fired at 90 degrees (not even -90 seems to have a problem), so maybe it has to do with overlapping paths?

For phetsims/QA/issues/29. I feel like there are many more permutations of the bug left to discover.

**Comment by jonathanolson** [comment] 2017-07-26 21:46
Is there a dev release I should be testing on Lave (iPad 2), or should I be testing off of master only?

Assuming I can reproduce, I'll look into layerSplit or renderer:canvas workarounds.

**Comment by jonathanolson** [comment] 2017-07-27 20:18
Applied a workaround that prevents the bugginess on my side (and I don't see any major performance decrease). @phet-steele, can you check master, or let me know if a dev version is needed?

**Comment by phet-steele** [comment] 2017-07-27 21:40
@jonathanolson, checked master, saw no problems! The performance was negligibly worse. There's more aliasing on the cannon now, but it's a fine trade off (and isn't that bad anyway).

**Comment by jonathanolson** [comment] 2017-07-27 22:06
Reopening, as I realized we probably don't want to force Canvas on the cannon on non-mobile-safari.

**Comment by jonathanolson** [comment] 2017-07-27 22:08
Applied. Feel free to verify when doing other testing, as it has a low chance of breaking.

**Comment by phet-steele** [comment] 2017-07-28 19:23
I said:
> I feel like there are many more permutations of the bug left to discover.

Yup! I was too quick to close this issue. @jonathanolson, here are some more ways to repro. These are on master now:


1. Intro screen
2. Angle cannon to 90
3. Zoom out twice (this is min zoom)
4. Fire - see flickering once the projectile starts to come back down. When the projectile lands, there will be no dots

Another:
1. Lab screen
2. Custom
3. Mass = 5000, Di = 3, G = 20, Air res checked, Alt = 0, Drag = 1
4. Cannon at 6 meters
5. Initial speed at 30 m/s
6. Fire at 35 degrees
7. BEFORE the projectile lands, adjust the cannon angle up to like 60 or so. The bottom of the Tracer tool should clip.

**Comment by jonathanolson** [comment] 2017-08-14 18:26
Less buggy version (with stroke instead): http://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.0-dev.10/projectile-motion_en.html

**Comment by jonathanolson** [comment] 2017-08-14 18:28
@ariel-phet, can you check whether this is acceptable? We can't reproduce any bugs with the specified procedures above, but changing the speed to 9 m/s (and somewhat 13 m/s) there were a few problems. It happens in general for way less configurations.

**Comment by ariel-phet** [comment] 2017-08-14 21:18
I think the behavior on dev.10 is completely acceptable now. I was able to reproduce with 9 m/s but that seems like a use case (highly zoomed out) that is rare and not particularly problematic.

Closing

**Closed by ariel-phet** 2017-08-14 21:18 UTC
Labels: type:bug
