### ISSUE TITLE
Consider adding an apex marker to the path

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#132] opened 2017-08-09 19:17 UTC
In #130, the timing dots were changed to 0.1 s intervals. One downside is that it'll be less likely to have a dot at (or very near) the apex. One possibility would be to add a marker at the apex. The marker would be visually distinct from the timing dots.

@andrea-phet does the current model allow you to easily find the apex of the path?

**Comment by amanda-phet** [comment] 2017-08-09 19:32
This would be super helpful for math teachers using this sim when teaching about parabolas.

**Comment by andrea-phet** [comment] 2017-08-10 15:27
It's not built into the model, but I think I could use basic physics equations to find the apex of the path that isn't affected by drag force, but I'm not sure how to calculate the apex for paths with drag force. @ariel-phet @arouinfar any ideas?

Another option would be to use one of the three data points between each timing dot, and use the data point that is closest to the apex. Because the model collects data points every 25 ms but only shows timing dots every 100 ms. It would be close, but it wouldn't be exactly the apex, and may be more off if we have, say, a projectile with very high speed with more spaced out data points.

**Comment by ariel-phet** [comment] 2017-08-10 16:28
@arouinfar @andrea-phet the apex will always occur when the velocity in the "y" direction is zero. So you probably just need to look for a velocity within some small range of zero for the vertical component of velocity. You might also be able to run a numerical solver to find the apex and @jonathanolson may have some idea.

You are also drawing the path, depending how the path is drawn, the apex will also be when the tangent to the path is a horizontal line, not sure if that information could be used to approximate the apex.

**Comment by andrea-phet** [comment] 2017-08-10 18:43
@arouinfar how does that look? A green dot represents the apex. It's calculated by doing a linear regression between two dots where the y velocity crosses over zero.

**Comment by ariel-phet** [comment] 2017-08-10 21:06
@andrea-phet It definitely passes the "eye-ball" test...Trying a bunch of conditions quickly the green dot seemed to visually be right at the apex. 

I will let @arouinfar make the call, but looking good to me.

**Comment by ariel-phet** [comment] 2017-08-11 15:21
Since @arouinfar is on vacation, since this looks good, closing

**Closed by ariel-phet** 2017-08-11 15:21 UTC
Labels: design:general, type:question
