### ISSUE TITLE
odd pink arc in control panel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#199] opened 2019-10-25 20:45 UTC
While responding to https://github.com/phetsims/projectile-motion/issues/197, I noticed an odd pink arc in over the word "Resistance", in this control panel in the _Lab_ screen. This was in projectile-motion sha a2510ac7aa48287e8264b2f5805ef66238068381.

<img width="300" alt="screenshot_1636" src="https://user-images.githubusercontent.com/3046552/67603424-08d54500-f736-11e9-9e57-714b133d3151.png">

**Comment by pixelzoom** [comment] 2019-10-25 20:46
This was in projectile-motion sha a2510ac7aa48287e8264b2f5805ef66238068381

**Comment by arouinfar** [comment] 2019-10-25 20:54
@pixelzoom the issue is that the Air Resistance checkbox should be left-aligned (as it is on other screens). The pink arc is the corresponding icon for air resistance. This is documented in the last checkbox in https://github.com/phetsims/projectile-motion/issues/177#issuecomment-540256334.

**Comment by arouinfar** [comment] 2019-10-25 20:54
Thanks for reporting and finding the offending commit.

**Comment by pixelzoom** [comment] 2019-10-25 21:29
Still a problem in master after pull-all.sh, projectile-motion df1a1fddd2954bb673f85572c35324bd9aee7897.

**Comment by pixelzoom** [comment] 2019-10-25 21:31
> @pixelzoom the issue is that the Air Resistance checkbox should be left-aligned (as it is on other screens).

It seems odd that this would cause the problem.  If the icon is for the Air Resistance checkbox, it should be part of that checkbox's label, and would move with the checkbox and text.   So I think you should take a look at how this icon was added -- sounds like it was added incorrectly.

**Comment by arouinfar** [comment] 2019-10-25 21:34
@pixelzoom currently the text and icons are separate nodes, but that is being addressed in #190 

> we can get rid of the checkboxAndIcon instrumentation, and just put the icon in the text Node given to checkbox.

**Comment by pixelzoom** [comment] 2019-10-25 21:35
The icon is indeed being added incorrectly.  Here's the code in LabProjectilePanel:

```js
    // air resistance
    const airResistanceLabel = new Text( airResistanceString, LABEL_OPTIONS );
    const airResistanceCheckbox = new Checkbox( airResistanceLabel, model.airResistanceOnProperty, {
      maxWidth: options.minWidth - AIR_RESISTANCE_ICON.width - 3 * options.xMargin,
      boxWidth: 18,
      tandem: tandem.createTandem( 'airResistanceCheckbox' )
    } );
    const airResistanceCheckboxAndIcon = new HBox( {
      spacing: options.xMargin,
      children: [ airResistanceCheckbox, AIR_RESISTANCE_ICON ]
    } );
```

It should be:

```js
    // air resistance
    const airResistanceCheckboxContent = new HBox( {
      spacing: options.xMargin,
      children: [ new Text( airResistanceString, LABEL_OPTIONS ), AIR_RESISTANCE_ICON ]
    } );
    const airResistanceCheckbox = new Checkbox( airResistanceCheckboxContent, model.airResistanceOnProperty, {
      maxWidth: options.minWidth - AIR_RESISTANCE_ICON.width - 3 * options.xMargin,
      boxWidth: 18,
      tandem: tandem.createTandem( 'airResistanceCheckbox' )
    } );
```

**Comment by zepumph** [comment] 2019-10-25 22:45
I did a few fixes here. I'll explain them individually:

* Surrounded the ICON in a containing Node, see https://github.com/phetsims/projectile-motion/issues/200
* made the Panel VBox align left, though I couldn't

>The icon is indeed being added incorrectly.

* Agreed, and that was being fixed in many cases at the tail end of https://github.com/phetsims/projectile-motion/issues/190. For PhET-iO it was beneficial to able to have the icon in the checkbox. This was the last occurrence that I hadn't gotten to yet over in the last checkbox of https://github.com/phetsims/projectile-motion/issues/177#issuecomment-540256334.
* I also fixed a bug where the lab screen combo box wasn't extending across the entire panel anymore, and I used that pattern in the intro screen too. 

All of these changes were closely aligned because this layout issue occurred in during active development. It may happen again before work is done in this sim, and I will be on the lookout. See https://github.com/phetsims/projectile-motion/issues/177 for central issue of work for the repo.

**Closed by zepumph** 2019-10-25 22:45 UTC
Labels: type:bug
