### ISSUE TITLE
CT cannot normalize a zero-magnitude vector

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-motion#240] opened 2021-01-22 19:30 UTC
```
projectile-motion : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611341282444/studio/?sim=projectile-motion&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1611341282444%22%2C%22timestamp%22%3A1611342660737%7D
Uncaught Error: Uncaught Error: Cannot normalize a zero-magnitude vector
Error: Cannot normalize a zero-magnitude vector
at Vector2.normalized (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611341282444/dot/js/Vector2.js:256:13)
at Line.getStartTangent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611341282444/kite/js/segments/Line.js:212:54)
at Line.get startTangent [as startTangent] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611341282444/kite/js/segments/Line.js:216:36)
at Line.areStrokedBoundsDilated (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611341282444/kite/js/segments/Segment.js:95:27)
at Shape.getStrokedBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611341282444/kite/js/Shape.js:1543:23)
at ArrowNode.computeShapeBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611341282444/scenery/js/nodes/Path.js:335:34)
at ArrowNode.updateSelfBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611341282444/scenery/js/nodes/Path.js:262:47)
at ArrowNode.validateSelfBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611341282444/scenery/js/nodes/Node.js:1140:40)
at ArrowNode.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611341282444/scenery/js/nodes/Node.js:1168:31)
at ProjectileNode.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611341282444/scenery/js/nodes/Node.js:1185:29)
id: Bayes Chrome
Snapshot from 1/22/2021, 11:48:02 AM
```

**Comment by jbphet** [comment] 2021-01-25 18:32
This is a duplicate of #234.  It is an intermittent problem that occurs during CT, and I'll get to it someday.  Just not today.  Closing.

**Closed by jbphet** 2021-01-25 18:32 UTC
Labels: type:automated-testing, type:duplicate
