### ISSUE TITLE
CT cannot add the same listener twice

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-motion#235] opened 2020-10-13 22:39 UTC
```
projectile-motion : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602624671211/projectile-motion/projectile-motion_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1602624671211%22%2C%22timestamp%22%3A1602625644387%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Cannot add the same listener twice
Error: Assertion failed: Cannot add the same listener twice
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602624671211/assert/js/assert.js:22:13)
at TinyEmitter.addListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602624671211/axon/js/TinyEmitter.js:99:15)
at BooleanProperty.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602624671211/axon/js/Property.js:386:25)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602624671211/scenery/js/listeners/PressListener.js:295:77
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602624671211/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602624671211/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602624671211/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602624671211/axon/js/Emitter.js:60:19)
at Proxy.push (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602624671211/axon/js/createObservableArray.js:264:32)
at FireListener.enter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602624671211/scenery/js/listeners/PressListener.js:674:23)
id: Bayes Chrome
Snapshot from 10/13/2020, 3:31:11 PM
```

**Comment by jbphet** [comment] 2021-02-05 00:31
I was talking with @zepumph, and he said that he thought this issue might be due to the phet-io work that was done on this sim a while back, so I'm assigning to him.  @zepumph - feel free to hit it back into my court if it makes sense to do so.

**Comment by zepumph** [comment] 2021-07-26 13:54
I haven't seen this on CT for a long long time.

**Comment by zepumph** [comment] 2021-07-26 21:21
I can't seem to reproduce this. I'll reopen if I catch it again.

**Closed by zepumph** 2021-07-26 21:21 UTC
Labels: type:automated-testing
